# kitty — Neon Grid (retro cyberpunk)
# Paleta: ~/dotfiles/colors.md

# ── Tipografía ────────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.5

# ── Ventana ───────────────────────────────────────────────────
window_padding_width    12
hide_window_decorations yes
background_opacity      0.92
confirm_os_window_close 0
enable_audio_bell       no
cursor_shape            beam
cursor_blink_interval   0.6

# ── Pestañas ──────────────────────────────────────────────────
tab_bar_style           powerline
tab_powerline_style     slanted
active_tab_foreground   #0d0221
active_tab_background   #ff2a6d
inactive_tab_foreground #6f6a8f
inactive_tab_background #1a1333

# ── Colores ───────────────────────────────────────────────────
foreground           #dee4ff
background           #0d0221
selection_foreground #0d0221
selection_background #05d9e8
cursor               #ff2a6d
cursor_text_color    #0d0221
url_color            #00b3fe

# black
color0  #1a1333
color8  #6f6a8f
# red
color1  #ff3864
color9  #ff5c8a
# green
color2  #05ffa1
color10 #6dffc2
# yellow
color3  #ffd319
color11 #ffe66d
# blue
color4  #00b3fe
color12 #55ccff
# magenta
color5  #ff2a6d
color13 #ff6e9f
# cyan
color6  #05d9e8
color14 #66eaf5
# white
color7  #dee4ff
color15 #f8f8ff

# ── Atajos ────────────────────────────────────────────────────
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t     new_tab_with_cwd
