# /etc/sddm.conf.d/10-neon-grid.conf
[Theme]
Current=where_is_my_sddm_theme

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1
